<a href="https://colab.research.google.com/github/beotavalo/MLOps-Zoomcamp/blob/main/DTC_MLOps_Zoomcamp_2024_H1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data download

import pandas as pd

# Define the URL where the parquet file is located
url_enero = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet"
url_febrero = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-02.parquet"
# Download the parquet file from the URL
!wget {url_enero }
!wget {url_febrero}

--2024-05-20 16:46:28--  https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 3.163.157.96, 3.163.157.133, 3.163.157.7, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|3.163.157.96|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47673370 (45M) [application/x-www-form-urlencoded]
Saving to: ‘yellow_tripdata_2023-01.parquet’

yellow_tripdata_202 100%[===================>]  45.46M   166MB/s    in 0.3s

2024-05-20 16:46:28 (166 MB/s) - ‘yellow_tripdata_2023-01.parquet’ saved [47673370/47673370]

--2024-05-20 16:46:28--  https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-02.parquet
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 3.163.157.96, 3.163.157.133, 3.163.157.7, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|3.163.157.96|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47748012 (46M) [application/x-www-form-urlencoded]
Saving to: ‘yellow_tripdata_2023-02.parquet’

yellow_tripdata_202 100%[===================>]  45.54M   201MB/s    in 0.2s

2024-05-20 16:46:28 (201 MB/s) - ‘yellow_tripdata_2023-02.parquet’ saved [47748012/47748012]

In [ ]:
# Read the downloaded parquet file into a pandas dataframe
df = pd.read_parquet("/content/yellow_tripdata_2023-01.parquet")

# Print the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3066766 entries, 0 to 3066765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[us](2), float64(12), int64(4), object(1)
memory usage: 444.6+ MB

In [ ]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [ ]:
df['duration'] = df['tpep_dropoff_datetime'] - df['tpep_pickup_datetime']

In [ ]:
#Transformar df_duration a minutos

df['duration'] = df['duration'].apply(lambda x: x / pd.Timedelta('1 minute'))

In [ ]:
df[0:20]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,duration
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00,8.433333
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00,6.316667
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00,12.750000
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25,9.616667
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00,10.833333
5,2,2023-01-01 00:50:34,2023-01-01 01:02:52,1.0,1.84,1.0,N,161,137,1,12.8,1.00,0.5,10.00,0.0,1.0,27.80,2.5,0.00,12.300000
6,2,2023-01-01 00:09:22,2023-01-01 00:19:49,1.0,1.66,1.0,N,239,143,1,12.1,1.00,0.5,3.42,0.0,1.0,20.52,2.5,0.00,10.450000
7,2,2023-01-01 00:27:12,2023-01-01 00:49:56,1.0,11.70,1.0,N,142,200,1,45.7,1.00,0.5,10.74,3.0,1.0,64.44,2.5,0.00,22.733333
8,2,2023-01-01 00:21:44,2023-01-01 00:36:40,1.0,2.95,1.0,N,164,236,1,17.7,1.00,0.5,5.68,0.0,1.0,28.38,2.5,0.00,14.933333
9,2,2023-01-01 00:39:42,2023-01-01 00:50:36,1.0,3.01,1.0,N,141,107,2,14.9,1.00,0.5,0.00,0.0,1.0,19.90,2.5,0.00,10.900000
10,2,2023-01-01 00:53:01,2023-01-01 01:01:45,1.0,1.80,1.0,N,234,68,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00,8.733333
11,1,2023-01-01 00:43:37,2023-01-01 01:17:18,4.0,7.30,1.0,N,79,264,1,33.8,3.50,0.5,7.75,0.0,1.0,46.55,2.5,0.00,33.683333
12,2,2023-01-01 00:34:44,2023-01-01 01:04:25,1.0,3.23,1.0,N,164,143,1,26.1,1.00,0.5,6.22,0.0,1.0,37.32,2.5,0.00,29.683333
13,2,2023-01-01 00:09:29,2023-01-01 00:29:23,2.0,11.43,1.0,N,138,33,1,44.3,6.00,0.5,13.26,0.0,1.0,66.31,0.0,1.25,19.900000
14,2,2023-01-01 00:33:53,2023-01-01 00:49:15,1.0,2.95,1.0,N,33,61,1,17.7,1.00,0.5,4.04,0.0,1.0,24.24,0.0,0.00,15.366667
15,2,2023-01-01 00:13:04,2023-01-01 00:22:10,1.0,1.52,1.0,N,79,186,1,10.0,1.00,0.5,1.25,0.0,1.0,16.25,2.5,0.00,9.100000
16,2,2023-01-01 00:45:11,2023-01-01 01:07:39,1.0,2.23,1.0,N,90,48,1,19.8,1.00,0.5,4.96,0.0,1.0,29.76,2.5,0.00,22.466667
17,1,2023-01-01 00:04:33,2023-01-01 00:19:22,1.0,4.50,1.0,N,113,255,1,20.5,3.50,0.5,4.00,0.0,1.0,29.50,2.5,0.00,14.816667
18,1,2023-01-01 00:03:36,2023-01-01 00:09:36,3.0,1.20,1.0,N,237,239,2,8.6,3.50,0.5,0.00,0.0,1.0,13.60,2.5,0.00,6.000000
19,1,2023-01-01 00:15:23,2023-01-01 00:29:41,2.0,2.50,1.0,N,143,229,2,15.6,3.50,0.5,0.00,0.0,1.0,20.60,2.5,0.00,14.300000

**Q2. Computing duration**

Now let's compute the duration variable. It should contain the duration of a ride in minutes.

What's the standard deviation of the trips duration in January?

In [ ]:
#Standart deviation

df['duration'].std()

42.59435124195458

**Q3. Dropping outliers**

Next, we need to check the distribution of the duration variable. There are some outliers. Let's remove them and keep only the records where the duration was between 1 and 60 minutes (inclusive).

What fraction of the records left after you dropped the outliers?

In [ ]:
# Remove them and keep only the records where the duration was between 1 and 60 minutes (inclusive).

df_filtered = df[(df['duration'] >= 1) & (df['duration'] <= 60)]

In [ ]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3009173 entries, 0 to 3066765
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
 19  duration               float64
dtypes: datetime64[us](2), float64(13), int64(4), object(1)
memory usage: 482.1+ MB

In [ ]:
#Fraction of record
(3009173/3066766)*100

98.1220282212598

**Q4. One-hot encoding**

Let's apply one-hot encoding to the pickup and dropoff location IDs. We'll use only these two features for our model.

    Turn the dataframe into a list of dictionaries (remember to re-cast the ids to strings - otherwise it will label encode them)
    Fit a dictionary vectorizer
    Get a feature matrix from it

What's the dimensionality of this matrix (number of columns)?

In [ ]:
# Turn the dataframe into a list of dictionaries (remember to re-cast the ids to strings - otherwise it will label encode them)
data_dict = df_filtered[['PULocationID', 'DOLocationID']].astype(str).to_dict(orient='records')

# Fit a dictionary vectorizer
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer()
dv.fit(data_dict)

# Get a feature matrix from it
X_train = dv.transform(data_dict)

# What's the dimensionality of this matrix (number of columns)?
print(X_train.shape)

(3009173, 515)

**Q5. Training a model**

Now let's use the feature matrix from the previous step to train a model.

    Train a plain linear regression model with default parameters
    Calculate the RMSE of the model on the training data

What's the RMSE on train?

In [ ]:
# Train a plain linear regression model with default parameters
# Calculate the RMSE of the model on the training data
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Train a plain linear regression model with default parameters
model = LinearRegression()
model.fit(X_train, df_filtered['duration'])

# Calculate the RMSE of the model on the training data
y_pred = model.predict(X_train)
rmse = np.sqrt(mean_squared_error(df_filtered['duration'], y_pred))

print("RMSE on train:", rmse)

RMSE on train: 7.649261929771859

**Q6. Evaluating the model**

Now let's apply this model to the validation dataset (February 2023).

What's the RMSE on validation?

In [ ]:
# Read the downloaded parquet file into a pandas dataframe
df_validation = pd.read_parquet("/content/yellow_tripdata_2023-02.parquet")

# Compute the duration
df_validation['duration'] = df_validation['tpep_dropoff_datetime'] - df_validation['tpep_pickup_datetime']
df_validation['duration'] = df_validation['duration'].apply(lambda x: x / pd.Timedelta('1 minute'))

# Filter the outliers
df_validation_filtered = df_validation[(df_validation['duration'] >= 1) & (df_validation['duration'] <= 60)]

# Transform the dataframe into a list of dictionaries
data_dict_validation = df_validation_filtered[['PULocationID', 'DOLocationID']].astype(str).to_dict(orient='records')

# Get the feature matrix
X_validation = dv.transform(data_dict_validation)

# Predict the duration
y_pred_validation = model.predict(X_validation)

# Calculate the RMSE
rmse_validation = np.sqrt(mean_squared_error(df_validation_filtered['duration'], y_pred_validation))

print("RMSE on validation:", rmse_validation)

RMSE on validation: 7.811818933419717